import { Product } from '@/types/product'

export const WHATSAPP_NUMBER = '923347573726'

export const products: Product[] = [
  {
    id: '1',
    slug: 'rose-quartz-lip-gloss',
    name: 'Rose Quartz Lip Gloss',
    collection: 'Premium Gloss Collection',
    sku: 'BB-LG-001',
    price: 1299,
    originalPrice: 1599,
    currency: 'PKR',
    currencySymbol: 'PKR',
    inStock: true,
    stockCount: 50,
    category: 'Lip Gloss',
    subcategory: 'Glossy Finish',
    finish: 'High Shine Glossy',
    highlights: [
      'Long-lasting 8+ hour formula',
      'Moisturizing with Vitamin E',
      'Non-sticky texture',
      'Beautiful rose quartz shade',
      'Cruelty-free & vegan',
      'Dermatologically tested',
    ],
    colors: [
      {
        name: 'Rose Quartz',
        hex: '#E8B4B8',
        images: [
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=85',
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=85',
          'https://images.unsplash.com/photo-1631214524020-7e18db10428a?w=900&q=85',
          'https://images.unsplash.com/photo-1583241800698-a8ca99cdb8e7?w=900&q=85',
        ],
      },
      {
        name: 'Coral Bliss',
        hex: '#FF7F7F',
        images: [
          'https://images.unsplash.com/photo-1631214524020-7e18db10428a?w=900&q=85',
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=85',
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=85',
          'https://images.unsplash.com/photo-1583241800698-a8ca99cdb8e7?w=900&q=85',
        ],
      },
      {
        name: 'Nude Silk',
        hex: '#C9A99D',
        images: [
          'https://images.unsplash.com/photo-1583241800698-a8ca99cdb8e7?w=900&q=85',
          'https://images.unsplash.com/photo-1631214524020-7e18db10428a?w=900&q=85',
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=85',
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=85',
        ],
      },
      {
        name: 'Berry Wine',
        hex: '#8B3E61',
        images: [
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=85',
          'https://images.unsplash.com/photo-1583241800698-a8ca99cdb8e7?w=900&q=85',
          'https://images.unsplash.com/photo-1631214524020-7e18db10428a?w=900&q=85',
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=85',
        ],
      },
    ],
    description: {
      overview: `The Rose Quartz Lip Gloss is a luxurious beauty essential, crafted for the modern woman who loves high-shine, moisturizing lip color. This premium formula delivers intense color payoff with a non-sticky, comfortable feel that lasts all day.\n\nEnriched with Vitamin E and natural oils, this lip gloss not only beautifies but also nourishes your lips. The glossy finish catches the light beautifully, making your lips look fuller and more defined.`,
      ingredients: `Our Rose Quartz Lip Gloss is formulated with carefully selected ingredients:\n\n• Vitamin E: Moisturizes and protects lips\n• Jojoba Oil: Provides long-lasting hydration\n• Coconut Oil: Nourishes and softens\n• Shea Butter: Keeps lips supple and smooth\n• Mica: Creates the beautiful glossy finish\n\nFree from parabens, sulfates, and harmful chemicals. Cruelty-free and vegan-friendly formula.`,
      howToUse: `For best results:\n\n1. Start with clean, dry lips\n2. Apply the lip gloss directly from the applicator wand\n3. Start from the center of your lips and work outward\n4. For extra volume, apply a second layer to the center of your lips\n5. Can be worn alone or over your favorite lipstick\n\nPro tip: Apply a bit to your cheekbones for a subtle, natural-looking highlight!`,
      benefits: `✨ Long-lasting 8+ hour wear\n✨ Intense moisturization\n✨ Non-sticky, comfortable formula\n✨ Beautiful high-shine finish\n✨ Makes lips appear fuller\n✨ Suitable for all skin types\n✨ Can be layered for intensity\n✨ Perfect for day and evening looks`,
    },
    ingredientsList: [
      { name: 'Vitamin E', purpose: 'Antioxidant & moisturizer', percentage: '5%' },
      { name: 'Jojoba Oil', purpose: 'Deep hydration', percentage: '10%' },
      { name: 'Coconut Oil', purpose: 'Nourishment', percentage: '8%' },
      { name: 'Shea Butter', purpose: 'Softening agent', percentage: '7%' },
      { name: 'Mica', purpose: 'Glossy finish', percentage: '3%' },
    ],
    productInfo: {
      crueltyFree: true,
      vegan: true,
      paraben: false,
      waterproof: false,
      longLasting: '8+ hours',
      skinType: ['All', 'Dry', 'Oily', 'Combination', 'Sensitive'],
    },
    deliveryInfo: {
      estimatedDays: '3–5 business days',
      regions: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'All Pakistan'],
      returnPolicy: '7-day easy returns. If you\'re not completely satisfied with your purchase, return it within 7 days for a full refund.',
      exchangePolicy: 'Exchange within 7 days if the shade doesn\'t suit you. We want you to love your Brella Beauty products!',
      freeShippingThreshold: 2500,
    },
    faqs: [
      {
        question: 'Is this lip gloss long-lasting?',
        answer: 'Yes! Our Rose Quartz Lip Gloss formula is designed to last 8+ hours. The staying power is excellent while maintaining the moisturizing benefits.',
      },
      {
        question: 'Is it sticky?',
        answer: 'Not at all! We\'ve formulated this gloss to be non-sticky and comfortable. You\'ll get beautiful shine without the tackiness.',
      },
      {
        question: 'Can I wear it over lipstick?',
        answer: 'Absolutely! This lip gloss works beautifully on its own or layered over your favorite lipstick for added shine and dimension.',
      },
      {
        question: 'Is it suitable for sensitive lips?',
        answer: 'Yes, our formula is dermatologically tested and suitable for all skin types, including sensitive lips. It\'s free from parabens and harsh chemicals.',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Ayesha Khan',
        location: 'Karachi',
        rating: 5,
        date: '2026-07-15',
        title: 'Best lip gloss ever!',
        comment: 'The Rose Quartz shade is absolutely gorgeous! The formula is so smooth and moisturizing. I\'ve been looking for a good local lip gloss brand and Brella Beauty exceeded my expectations.',
        verified: true,
        helpful: 24,
      },
      {
        id: 'r2',
        author: 'Sara Ahmed',
        location: 'Lahore',
        rating: 5,
        date: '2026-07-20',
        title: 'Love the shine!',
        comment: 'This lip gloss gives the perfect amount of shine without being too much. It\'s not sticky at all and lasts throughout the day. Highly recommend!',
        verified: true,
        helpful: 18,
      },
      {
        id: 'r3',
        author: 'Zara Malik',
        location: 'Islamabad',
        rating: 5,
        date: '2026-07-25',
        title: 'My new favorite',
        comment: 'I ordered the Berry Wine shade and it\'s perfect for evening looks. The quality is amazing for the price. Will definitely buy more shades!',
        verified: true,
        helpful: 15,
      },
    ],
    averageRating: 5,
    totalReviews: 3,
    relatedProductIds: [],
    tags: ['lip gloss', 'glossy', 'moisturizing', 'long-lasting', 'cruelty-free', 'vegan', 'best-seller'],
    whatsappNumber: WHATSAPP_NUMBER,
    metaTitle: 'Rose Quartz Lip Gloss - Premium Glossy Finish | Brella Beauty',
    metaDescription: 'Shop our luxurious Rose Quartz Lip Gloss. Long-lasting 8+ hour formula, moisturizing with Vitamin E, non-sticky texture. Cruelty-free & vegan. Available in 4 stunning shades. Order via WhatsApp!',
  },
]
